# Generated by Django 4.1.6 on 2023-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('media', models.FileField(null=True, upload_to='audio', verbose_name='Media')),
                ('category', models.CharField(max_length=30, null=True, verbose_name='Category')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Duration')),
            ],
        ),
    ]
