# Generated by Django 4.1.6 on 2023-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_slogan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40, null=True, verbose_name='Location')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('facebook_url', models.CharField(max_length=40, null=True, verbose_name='Facebook')),
                ('instagram_url', models.CharField(max_length=40, null=True, verbose_name='Instagram')),
                ('youtube_url', models.CharField(max_length=40, null=True, verbose_name='Youtube')),
                ('phone', models.CharField(max_length=14, null=True, verbose_name='Phone Number')),
            ],
        ),
    ]
