# Generated by Django 4.1.6 on 2023-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_orgdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogan',
            name='caption',
            field=models.FileField(null=True, upload_to='vtt', verbose_name='Caption'),
        ),
    ]
