# Generated by Django 4.1.6 on 2023-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_slogan_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phonenumber', models.CharField(max_length=14, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('postalCode', models.IntegerField(null=True, verbose_name='Postal Code')),
                ('requirement', models.CharField(choices=[('', 'Select Type'), ('type1', 'Type 1 - Planetary transit'), ('type2', 'Type 2 - House warming'), ('type3', 'Type 3 - Telugu Sampradaya'), ('type4', 'Type 4 - Homam'), ('type5', 'Type 5 - Sirartha'), ('type6', 'Type 6 - As per Telugu tradition')], max_length=50, null=True, verbose_name='Requirement')),
                ('services', models.CharField(choices=[('0', 'Select Services')], max_length=50, null=True, verbose_name='Services')),
                ('mode', models.CharField(choices=[('0', 'Select Mode'), ('1', 'Offline'), ('2', 'Online')], max_length=50, null=True, verbose_name='Mode')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('others', models.TextField(null=True, verbose_name='Others')),
            ],
        ),
    ]
